export function is3DGeometry(geometryType) {
  return [
    'PointZ',
    'PointM',
    'PointZM',
    'Point25D',
    'MultiPointZ',
    'MutliPointM',
    'MultiPointZM',
    'MultiPoint25D',
    'LineStringZ',
    'LineStringM',
    'LineStringZM',
    'LineString25D',
    'MultiLineStringZ',
    'MultiLineStringM',
    'MultiLineStringZM',
    'MultiLineString25D',
    'LineZ',
    'LineM',
    'LineZM',
    'Line25D',
    'MultiLineZ',
    'MultiLineM',
    'MultiLineZM',
    'MultiLine25D',
    'PolygonZ',
    'PolygonM',
    'PolygonZM',
    'Polygon25D',
    'MultiPolygonZ',
    'MultiPolygonM',
    'MultiPolygonZM',
    'MultiPolygon25D'
  ].find(type3D => type3D === geometryType);
}