const Fonts = {
  fontawsome: {
    versions:{
      '4': {
        'change-map': "fa fa-map-signs",
        map: "fa fa-map-o",
        file: "fa fa-file-code-o",
        marker: "fa fa-map-marker",
        relation: "fa fa-sitemap",
        tools: "fa fa-gears",
        tool: "fa fa-gear",
        search: "fa fa-search",
        print: "fa fa-print",
        info: "fa fa-info-circle",
        'info-circle': "fa fa-info-circle",
        globe: "fa fa-globe",
        mail: "fa fa-envelope-o",
        mobile: "fa fa-mobile",
        fax: "fa fa-fax",
        user: "fa fa-user",
        bars: "fa fa-bars",
        uncheck: "fa fa-square-o",
        check: "fa fa-check-square-o",
        filluncheck: "fa fa-square",
        table: "fa fa-table",
        trash: "fa fa-trash",
        'trash-o':"fa fa-trash-o",
        pencil: "fa fa-pencil",
        'ellips-h': "fa fa-ellips-h",
        'arrow-up': "fa fa-chevron-up",
        'arrow-down': "fa fa-chevron-down",
        'arrow-left': "fa fa-chevron-left",
        'arrow-right': "fa fa-chevron-right",
        'angle-up': "fa fa-angle-up",
        'angle-down': "fa fa-angle-down",
        'angle-left': "fa fa-angle-left",
        'angle-right': "fa fa-angle-right",
        'caret-up': "fa fa-caret-up",
        'caret-down': "fa fa-caret-down",
        'caret-left': "fa fa-caret-left",
        'caret-right': "fa fa-caret-right",
        'empty-circle': "fa fa-circle-o",
        'cloud-upload': "fa fa-cloud-upload",
        spinner: "fa fa-spinner",
        minus: "fa fa-minus",
        plus: "fa fa-plus",
        grid: "fa fa-th",
        home: "fa fa-home",
        folder: "fa fa-folder",
        'sign-out': "fa fa-sign-out",
        close: "fa fa-times",
        time: "fa fa-clock-o",
        calendar: "fa fa-calendar",
        list: "fa fa-list-alt",
        link: "fa fa-link",
        unlink: " fa-chain-broken",
        eye: "fa fa-eye",
        'eye-close': "fa fa-eye-slash",
        save: "fa fa-floppy-o",
        pdf: "fa fa-file-pdf-o",
        image: "fa fa-file-image-o",
        video: "fa fa-file-video-o",
        unknow:"fa fa-question-circle-o",
        zip: "fa file-zip-o",
        text: "fa fa-file-text-o",
        excel: "fa fa-file-excel-o",
        csv: "fa fa-file-excel-o",
        ppt: "fa fa-file-powerpoint-o",
        circle: "fa fa-circle",
        download: "fa fa-download",
        calculator: "fa fa-calculator",
        picture: "fa fa-picture-o",
        crosshairs: "fa fa-crosshairs",
        keyboard: "fa fa-keyboard-o",
        'file-download': "fa fa-download",
        copy: "fa fa-clone",
        draw: "fa fa-plus",
        chart: "fa fa-bar-chart",
        'chart-line': "fa fa-chart-line",
        run: "fa fa-play",
        warning:"fa fa-exclamation-circle",
        alert: "a fa-exclamation-triangle",
        crosshairs: "fa fa-crosshairs",
        success: "fa fa-check-circle-o",
        back: "fa fa-chevron-circle-left",
        'file-upload': "fa fa-file-upload"
      },
      '5': {
        'change-map': "fas fa-map-signs",
        map: "far fa-map",
        file: "fas fa-file-code",
        marker: "fas fa-map-marker-alt",
        relation: "fas fa-sitemap",
        tools: "fas fa-cogs",
        tool: "fas fa-cog",
        search: "fas fa-search",
        print: "fas fa-print",
        info: "fas fa-info-circle",
        'info-circle': "fas fa-info-circle",
        globe: "fas fa-globe",
        mail: "fas fa-envelope",
        mobile: "fas fa-mobile",
        fax: "fas fa-fax",
        user: "fas fa-user",
        bars: "fas fa-bars",
        uncheck: "far fa-square",
        check: "far fa-check-square",
        filluncheck: "fas fa-square",
        table: "fas fa-table",
        trash: "fas fa-trash",
        'trash-o':"far fa-trash-alt",
        pencil: "fas fa-pencil-alt",
        'ellips-h': "fas fa-ellips-h",
        'arrow-up': "fas fa-chevron-up",
        'arrow-down': "fas fa-chevron-down",
        'arrow-left': "fas fa-chevron-left",
        'arrow-right': "fas fa-chevron-right",
        'caret-up': "fas fa-caret-up",
        'caret-down': "fas fa-caret-down",
        'caret-left': "fas fa-caret-left",
        'caret-right': "fas fa-caret-right",
        'empty-circle': "far fa-circle",
        'cloud-upload': "fas fa-cloud-upload-alt",
        spinner: "fas fa-spinner",
        minus: "fas fa-minus",
        plus: "fas fa-plus",
        grid: "fas fa-th",
        home: "fas fa-home",
        folder: "fas fa-folder",
        'sign-out': "fas fa-sign-out-alt",
        close: "fas fa-times",
        time: "far fa-clock",
        calendar: "fas fa-calendar-alt",
        list: "fas fa-list-alt",
        link: "fas fa-link",
        unlink: "fas fa-unlink",
        eye: "far fa-eye",
        'eye-close': "far fa-eye-slash",
        save: "far fa-save",
        pdf: "fas fa-file-pdf",
        image: "far fa-image",
        video: "far fa-file-video",
        unknow:"far fa-question-circle",
        zip: "far fa-file-archive",
        text: "far fa-file-alt",
        excel: "far fa-file-excel",
        csv: "fas fa-file-csv",
        ppt: "far fa-file-powerpoint",
        circle: "fas fa-circle",
        download: "fas fa-download",
        calculator: "fas fa-calculator",
        picture: "far fa-image",
        crosshairs: "fas fa-crosshairs",
        keyboard: "far fa-keyboard",
        'file-download':"fas fa-file-download",
        copy: "far fa-copy",
        draw: "fas fa-draw-polygon",
        chart: "fas fa-chart-bar",
        'chart-line': "fas fa-chart-line",
        run: "fas fa-play",
        warning: "fas fa-exclamation-circle",
        alert: "fas fa-exclamation-triangle",
        crosshairs: "fas fa-crosshairs",
        success: "far fa-check-circle",
        back: "fas fa-chevron-circle-left",
        'file-upload': "fas fa-file-upload",
        wifi: "fas fa-wifi",
        mouse: "fas fa-mouse",
        'copy-paste': "far fa-copy",
        'vector-square': "fas fa-vector-square",
        download: "fas fa-download",
        credits: "fas fa-euro-sign"
      }
    }
  }
};

module.exports = Fonts;
